### PR TITLE
Fix accessing member of nil value.

### PR DESCRIPTION
**Pull request by tinkernels**
ref: load-subtitles

### CODE REVIEW

**Comment by tomasklaen** [comment]
I think this needs a bit different approach:

```lua
if path then
	if is_protocol(path) then
		path = false
	else
		local serialized_path = serialize_path(path)
		path = serialized_path ~= nil and serialized_path.dirname or false
	end
end
if not path then
	path = os.getenv("HOME")
end
open_file_navigation_menu(
	path,
```

Just paste this there, test that it works, and update the PR.

**Comment by tinkernels** [comment]
> I think this needs a bit different approach:
> 
> ```lua
> if path then
> 	if is_protocol(path) then
> 		path = false
> 	else
> 		local serialized_path = serialize_path(path)
> 		path = serialized_path ~= nil and serialized_path.dirname or false
> 	end
> end
> if not path then
> 	path = os.getenv("HOME")
> end
> open_file_navigation_menu(
> 	path,
> ```
> 
> Just paste this there, test that it works, and update the PR.

Modified and tested here.

**Comment by tomasklaen** [comment]
You forgot to pass the `path` we've just spent the last 11 lines normalizing into `open_file_navigation_menu(path)` as in my snippet. It's still accepting `serialize_path(path).dirname`.

**Comment by tinkernels** [comment]
> You forgot to pass the `path` we've just spent the last 11 lines normalizing into `open_file_navigation_menu(path)` as in my snippet. It's still accepting `serialize_path(path).dirname`.

Modified now.

**Pull request merged**
